## Import the relevant libraries

In [1]:
import numpy as np

## Declaring scalars, vectors, and matrices

### Scalars

In [3]:
s = 5

In [4]:
s

5

### Vectors

In [5]:
v = np.array([5,-2,4])


In [6]:
v

array([ 5, -2,  4])

### Matrices

In [7]:
m = np.array([[5, 12, 6],
             [-3, 0, 14]])

In [8]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data types

In [9]:
type(s)

int

In [10]:
type(v)

numpy.ndarray

### Data shapes

In [11]:
m.shape

(2, 3)

In [12]:
v.shape

(3,)

 # Tensor

### Creating a tensor

In [13]:
m1 = np.array([[5,12,6],
               [-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [14]:
m2 = np.array([[9,8,7],
               [1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [15]:
t = np.array([m1, m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [16]:
t.shape

(2, 2, 3)

### Adding Matrices

In [17]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

### Subtracting Matrices

In [18]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

### Transposing matrices

In [19]:
a1 = np.array([[5,12,6],
               [-3,0,14]])
a1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [20]:
a1.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

### Transposing vectors

In [21]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [22]:
x.shape

(3,)

In [23]:
x.T

array([1, 2, 3])

In [24]:
x_reshaped = x.reshape(1,3)

In [25]:
x_reshaped

array([[1, 2, 3]])

In [26]:
x_reshaped.T

array([[1],
       [2],
       [3]])

### Dot product

In [27]:
v1 = np.array([2,8,-4])
v2 = np.array([1,-7,3])


In [28]:
np.dot(v1, v2)

np.int64(-66)

In [32]:
A = np.array([[5,12,6],
               [-3,0,14]])
A.shape

(2, 3)

In [38]:
B = np.array([[2,-1],[8,0],[3,0]])
B.shape

(3, 2)

In [39]:
A_x_B = np.dot(A,B)
A_x_B

array([[124,  -5],
       [ 36,   3]])