## Import the relevant libraries

In [2]:
import numpy as np

## Declaring scalars, vectors, and matrices

### Scalars

In [1]:
s = 5

In [3]:
s

5

### Vectors

In [4]:
v = np.array([5,-2,4])


In [5]:
v

array([ 5, -2,  4])

### Matrices

In [8]:
m = np.array([[5, 12, 6],
             [-3, 0, 14]])

In [9]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data types

In [10]:
type(s)

int

In [11]:
type(v)

numpy.ndarray

### Data shapes

In [13]:
m.shape

(2, 3)

In [14]:
v.shape

(3,)

 # Tensor

### Creating a tensor

In [ ]:
m1 = np.array([[5,12,6],
               [-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [ ]:
m2 = np.array([[9,8,7],
               [1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [17]:
t = np.array([m1, m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [18]:
t.shape

(2, 2, 3)