In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv("1.02. Multiple linear regression.csv")

In [3]:
data

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

# Create the multiple LR

### Declare the dependent and independent variables

In [5]:
y = data['GPA']
x = data[['SAT', 'Rand 1,2,3']]

In [6]:
x.shape

(84, 2)

### Regression itselt

In [7]:
reg = LinearRegression()

In [8]:
reg.fit(x, y)

LinearRegression()

In [8]:
reg.intercept_

0.29603261264909264

In [9]:
reg.coef_

array([ 0.00165354, -0.00826982])

### Calculating the R-squared

In [10]:
reg.score(x, y)

0.40668119528142843

### Formula for Adjusted R^2

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

##### n = 84 (the number of observations)
##### p = 2 (the number of predictors)

In [9]:
r2 = reg.score(x, y)
n = x.shape[0]
p = x.shape[1]

In [10]:
def adj_r2(r2, n, p):
    adj_r2 = 1 - (1 - r2)*(n-1)/(n-p-1)
    return adj_r2

adj_r2(r2, n, p)

0.3920313482513401

### Feature selection

In [12]:
from sklearn.feature_selection import f_regression

In [13]:
f_regression(x, y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [14]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [15]:
p_values.round(3)

array([0.   , 0.676])

### Creating a summary table

In [16]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [17]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [18]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676